# Generated by Django 5.0.4 on 2024-08-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='profil',
        ),
    ]
