# Generated by Django 5.0.4 on 2024-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_reaction_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='profile/1678452520759.jpg', upload_to='profile/'),
        ),
    ]
