# Generated by Django 5.0.4 on 2024-08-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='etablissement_freq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='publicatio/'),
        ),
    ]
