# Generated by Django 5.0.4 on 2024-08-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='biographie',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='profil',
            name='parcours_disponible',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profil',
            name='slogan',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
